// beer-app/src/Menu.jsx
import React from 'react';
import { NavLink } from 'react-router-dom';
import { connect } from 'react-redux';

import { sumPrice } from './lib';

const Menu = ({ basket }) => (
  <nav className="navbar navbar-inverse navbar-fixed-top">
    <div className="container">
      <div className="navbar-header">
        <NavLink to="/" className="navbar-brand">Zenika Ecommerce</NavLink>
      </div>
      <div className="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul className="nav navbar-nav">
          <li>
            <NavLink to="/basket">
              Accéder à votre panier ({
                basket.length > 0
                  ? `${basket.length} articles - ${basket.reduce(sumPrice, 0)}€`
                  : 'vide'
              })
            </NavLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
);

const mapStateToProps = (state) => ({
  basket: state.basket.beers
});

export default connect(mapStateToProps)(Menu);

// beer-app/src/app/menu/menu.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {Beer} from "../beer";

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit {

  @Input()
  basket: Beer[];

  constructor() { }


  ngOnInit() {
  }

  calculerTotal(): number {

/*    let total: number = 0.0;
    for(let beer of this.basket){
      total += beer.price;
    }

    return total;*/


    return this.basket.reduce( (a, b) => a + b.price, 0);
  }
}

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="#" class="navbar-brand">Zenika Ecommerce</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <a href="#">Accéder à votre panier ({{basket.length}} articles - {{calculerTotal() | currency }} )</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
