// beer-app/src/Beer.jsx
import React from 'react';

import { currency, uppercase } from './lib';

const Beer = ({ beer, onClick }) => beer.stock === 0 ? null : (
  <div className="col-sm-4 col-lg-4 col-md-4">
    <div className={'thumbnail' + (beer.stock === 1 ? ' last' : '')}>
      <img src={beer.image} alt="" />
      <div className="caption">
        <h4 className="pull-right">{currency(beer.price)}</h4>
        <h4>
          <span>{uppercase(beer.label)}</span>
        </h4>
        <p>{beer.description}</p>
      </div>
      <div className="ratings">
        <p>
          <span className="glyphicon glyphicon-star"></span>
          <span className="glyphicon glyphicon-star"></span>
          <span className="glyphicon glyphicon-star"></span>
          <span className="glyphicon glyphicon-star"></span>
          <span className="glyphicon glyphicon-star-empty"></span>
        </p>
        <button onClick={() => onClick(beer)} type="button" className="pull-right btn btn-primary" aria-label="Ajoutez au Panier">Ajouter</button>
      </div>
    </div>
  </div>
);

export default Beer;

// beer-app/src/app/beer/beer.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Beer } from '../beer';

@Component({
  selector: 'app-beer',
  templateUrl: './beer.component.html',
  styleUrls: ['./beer.component.css']
})
export class BeerComponent implements OnInit {

  @Input() beer: Beer;

  constructor() { }

  ngOnInit() {
  }
}

<div class="col-sm-4 col-lg-4 col-md-4">
  <div class='thumbnail'>
    <img src="{{beer.image}}" alt="" />
    <div class="caption">
      <h4 class="pull-right">{{beer.price | currency}}</h4>
      <h4>
        <span>{{beer.label}}</span>
      </h4>
      <p>{{beer.description}}</p>
    </div>
    <div class="ratings">
      <p>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star"></span>
        <span class="glyphicon glyphicon-star-empty"></span>
      </p>
      <strong *ngIf="beer.stock == 0">Rupture de stock!</strong>
      <button [disabled]="beer.stock == 0" (click)="onAddBeer()" type="button" class="pull-right btn btn-primary" aria-label="Ajoutez au Panier">Ajouter</button>
    </div>
  </div>
</div>
